In [5]:
import numpy as np

In [6]:
x = np.array([1, 2, 3, 6, 5, 4, 7])

In [8]:
print(type(x))
# row X column, type ndarray

<class 'numpy.ndarray'>


In [10]:
y = np.array([[1, 4, 2], [5, 6, 8]])
print(y)

[[1 4 2]
 [5 6 8]]


In [14]:
y.shape #row X colm

(2, 3)

In [18]:
y.size #total no of elements

6

In [23]:
z = y.reshape(3, 2) #change the shape of an array
print(z)

[[1 4]
 [2 5]
 [6 8]]


In [27]:
print(y[1, 0]) #access individual elements of array

5


In [30]:
print(y[:, 1]) #slicing of array

[4 6]


In [33]:
x1 = np.linspace(1, 10, 15) #used to print 15 values which are evenly spaced over the given interval(1, 10)

In [34]:
x1

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [40]:
x2 = np.array([1, 2, 4, 3, 5, 6, 7, 8, 9])
print("The maximum element is: ", x2.max())
print("The minimum element is: ", x2.min())
print("The sum of all element is: ", x2.sum()) # Finding min, max, and sum of all the elements

The maximum element is:  9
The minimum element is:  1
The sum of all element is:  45


In [52]:
x2.base is None

True

In [59]:
x3 = np.array([[1, 2, 4], [3, 5, 6], [7, 8, 9]])
print("The maximum element is: ", x3.max(axis = 1)) #0 = row, 1 = colm
print("The minimum element is: ", x3.min(axis = 0))
print("The sum of all element is: ", x3.sum(axis = 1)) # Finding min, max, and sum of all the elements along row and column

The maximum element is:  [4 6 9]
The minimum element is:  [1 2 4]
The sum of all element is:  [ 7 14 24]


In [64]:
x4 = np.array([[1, 2, 4], [3, 5, 6], [7, 8, 9]])
x5 = np.array([[15, 20, 46], [95, 53, 66], [19, 80, 6]])
print("The sum of array: \n", x4+x5)

The sum of array: 
 [[16 22 50]
 [98 58 72]
 [26 88 15]]


In [63]:
print("The product of array: \n", x4*x5)

The product of array: 
 [[ 15  40 184]
 [285 265 396]
 [133 640  54]]


In [66]:
print("The quotient of array: \n", x5/x4)

The quotient of array: 
 [[15.         10.         11.5       ]
 [31.66666667 10.6        11.        ]
 [ 2.71428571 10.          0.66666667]]


In [67]:
print("The sum of array: \n", x4-x5)

The sum of array: 
 [[-14 -18 -42]
 [-92 -48 -60]
 [-12 -72   3]]


In [68]:
print("array are vertically concatenated \n", np.vstack((x4,x5)))

array are vertically concatenated 
 [[ 1  2  4]
 [ 3  5  6]
 [ 7  8  9]
 [15 20 46]
 [95 53 66]
 [19 80  6]]


In [69]:
print("array are horizontally concatenated \n", np.hstack((x4,x5)))

array are horizontally concatenated 
 [[ 1  2  4 15 20 46]
 [ 3  5  6 95 53 66]
 [ 7  8  9 19 80  6]]


In [70]:
x4

array([[1, 2, 4],
       [3, 5, 6],
       [7, 8, 9]])

In [71]:
x5

array([[15, 20, 46],
       [95, 53, 66],
       [19, 80,  6]])

In [72]:
g = np.hstack((x4,x5))

In [73]:
g

array([[ 1,  2,  4, 15, 20, 46],
       [ 3,  5,  6, 95, 53, 66],
       [ 7,  8,  9, 19, 80,  6]])

In [75]:
np.zeros((3, 3)) #process to create enpty matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.ones((3, 3)) #process to create unity matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.eye(3, 3) #process to create identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
f = [1, 4, 3, 7, 8, 5, 9, 0, 2, 6]
k = np.asarray(f) #How to create an array from a list

In [79]:
k

array([1, 4, 3, 7, 8, 5, 9, 0, 2, 6])

In [80]:
f

[1, 4, 3, 7, 8, 5, 9, 0, 2, 6]

In [86]:
np.arange(0, 10, 1, int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
x6 = [0.23, 0.09, 1.2, 1.24, 9.99]  
np.fix(x6) 

array([0., 0., 1., 1., 9.])

In [90]:
np.floor(x6) #Rounds off to the previous integer

array([0., 0., 1., 1., 9.])

In [91]:
np.ceil(x6) #Rounds off to the next integer

array([ 1.,  1.,  2.,  2., 10.])

In [93]:
np.char.add(['Ishan '], ['Mitra'])

array(['Ishan Mitra'], dtype='<U11')

In [96]:
np.char.add(['Ishan ','Tushan ', 'Prodosh '], ['Mitra', 'mitra', 'Mitra'])

array(['Ishan Mitra', 'Tushan mitra', 'Prodosh Mitra'], dtype='<U13')

In [101]:
np.char.multiply("Ishan ", 4)

array('Ishan Ishan Ishan Ishan ', dtype='<U24')

In [106]:
np.multiply(64, 64)
np.sqrt(64)

8.0

In [115]:
np.char.center("", 10, '-')

array('----------', dtype='<U10')

In [126]:
for i in range(20, 0, -1):
    print(np.char.center("Tushan", i, '*'))
    #i = i - 1
    

*******Tushan*******
*******Tushan******
******Tushan******
******Tushan*****
*****Tushan*****
*****Tushan****
****Tushan****
****Tushan***
***Tushan***
***Tushan**
**Tushan**
**Tushan*
*Tushan*
*Tushan
Tushan
Tusha
Tush
Tus
Tu
T


In [120]:
np.char.center("", 10, '*')

array('**********', dtype='<U10')

In [ ]:
np.up